### ISSUE TITLE
Release of pretrained weights and link to training data

### ISSUE THREAD

**Issue by remtav** [Jack-bo1220/MSResNet-via-SSL#1]
Hi! Thanks for publishing your code. Will you publish pretrained weights and a link to the training data used in the article? It seems in the current state of the repo, results from the article cannot be reproduced easily. Publishing pretrained weights would also help assessing the performance on the 2020 Gaofen Challenge water-body.

**Comment by Jack-bo1220** [comment]
Hi @remtav,
my apologies for the late reply.
The pretrained model and guidelines is available now.
